// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL5Ypf_VE8OuZtcqs56lDlMNcdnffdhx8',
    appId: '1:380469602767:web:b1d664d726db742bf38aba',
    messagingSenderId: '380469602767',
    projectId: 'e-commerce-app-ac6ec',
    authDomain: 'e-commerce-app-ac6ec.firebaseapp.com',
    storageBucket: 'e-commerce-app-ac6ec.appspot.com',
    measurementId: 'G-0P56TSS49V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArFYFjGWOux0a1GnuMgb7e4QIAEAzFahw',
    appId: '1:380469602767:android:778dc1985588f843f38aba',
    messagingSenderId: '380469602767',
    projectId: 'e-commerce-app-ac6ec',
    storageBucket: 'e-commerce-app-ac6ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-yzoRnqa2vb-aARBI0X2fiXYEvpM8mwI',
    appId: '1:380469602767:ios:f83a6a5174a5a1f5f38aba',
    messagingSenderId: '380469602767',
    projectId: 'e-commerce-app-ac6ec',
    storageBucket: 'e-commerce-app-ac6ec.appspot.com',
    iosBundleId: 'com.example.eCommerce.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-yzoRnqa2vb-aARBI0X2fiXYEvpM8mwI',
    appId: '1:380469602767:ios:f83a6a5174a5a1f5f38aba',
    messagingSenderId: '380469602767',
    projectId: 'e-commerce-app-ac6ec',
    storageBucket: 'e-commerce-app-ac6ec.appspot.com',
    iosBundleId: 'com.example.eCommerce.RunnerTests',
  );
}
